export const ECOSYSTEMS = [
  {
    id: 1,
    image: "/ecosystem/exchange.svg",
    title: "DECENTRALIZED EXCHANGE",
    shortDescription: (
      <p className="ecosystem-description">
        The EDDASwap DEX facilitates permission-less listing and trading of
        crypto assets across blockchains such as Ethereum, Polygon (MATIC),
        Binance Smart Chain and Polkadot. EDDASwap has added security features
        such as "Liquidity Lock", whereby users that list their token onto
        EDDASwap will have the ability to lock in the liquidity to gain trust
        and credibility. A part of the trading fees generated on the DEX will be
        used to buy EDDA tokens from the open market and the same will be
        distributed to those staking EDDA. The LP tokens generated by providing
        liquidity to the EDDASwap DEX can be staked to earn a range of benefits
        such as EDDASwap\'s exclusive NFTs.
      </p>
    ),
    buttonLabel: "EDDASwap DEX",
    link: "https://dex.eddaswap.com/exchange",
  },
  {
    id: 2,
    image: "/ecosystem/nft.svg",
    title: "NON-FUNGIBLE TOKENS (NFT)",
    shortDescription: (onToggle) => (
      <p className="ecosystem-description">
        Our <span>NFT platform</span> is live since March 2021. EDDASwap has
        partnered with leading global artists, 3D motion graphic designers and
        producers to create a specially curated NFT collection which has been in
        production since Q2 2020. Our Ultra Rare NFTs have gone viral globally
        and have been shared, retweeted and posted by Cameron Winklevoss, Tyler
        Winklevoss, Jason A Williams and many global influencers. EDDA token
        holders and stakers have exclusive access to EDDASwap’s NFT collection
        created by well-known artists including&nbsp;
        <a
          className="ecosystem-artist"
          href="https://app.eddaswap.com/nft-detail?id=52"
          target="_blank"
          rel="noopener noreferrer"
        >
          OZ
        </a>
        ,&nbsp;
        <a
          className="ecosystem-artist"
          href="https://app.eddaswap.com/nft-detail?id=81"
          target="_blank"
          rel="noopener noreferrer"
        >
          Cyrus James Khan
        </a>
        ,&nbsp;
        <a
          className="ecosystem-artist"
          href="https://app.eddaswap.com/nft-detail?id=13"
          target="_blank"
          rel="noopener noreferrer"
        >
          Primal Cypher
        </a>
        ,&nbsp;
        <a
          className="ecosystem-artist"
          href="https://app.eddaswap.com/nft-detail?id=63"
          target="_blank"
          rel="noopener noreferrer"
        >
          Marnik
        </a>
        ,&nbsp;
        <a
          className="ecosystem-artist"
          href="https://app.eddaswap.com/nft-detail?id=71"
          target="_blank"
          rel="noopener noreferrer"
        >
          Yana Khvan
        </a>
        ,&nbsp;
        <a
          className="ecosystem-artist"
          href="https://app.eddaswap.com/nft-detail?id=78"
          target="_blank"
          rel="noopener noreferrer"
        >
          BatMax
        </a>
        ,&nbsp; ...{" "}
        <span onClick={onToggle} className="ecosystem-more">
          More
        </span>
      </p>
    ),
    longDescription: (onToggle) => (
      <p className="ecosystem-description">
        Our NFT platform is live since March 2021. EDDASwap has partnered with
        leading global artists, 3D motion graphic designers and producers to
        create a specially curated NFT collection which has been in production
        since Q2 2020. Our Ultra Rare NFTs have gone viral globally and have
        been shared, retweeted and posted by Cameron Winklevoss, Tyler
        Winklevoss, Jason A Williams and many global influencers. EDDA token
        holders and stakers have exclusive access to EDDASwap’s NFT collection
        created by well-known artists including&nbsp;
        <a
          className="ecosystem-artist"
          href="https://app.eddaswap.com/nft-detail?id=52"
          target="_blank"
          rel="noopener noreferrer"
        >
          OZ
        </a>
        ,&nbsp;
        <a
          className="ecosystem-artist"
          href="https://app.eddaswap.com/nft-detail?id=81"
          target="_blank"
          rel="noopener noreferrer"
        >
          Cyrus James Khan
        </a>
        ,&nbsp;
        <a
          className="ecosystem-artist"
          href="https://app.eddaswap.com/nft-detail?id=13"
          target="_blank"
          rel="noopener noreferrer"
        >
          Primal Cypher
        </a>
        ,&nbsp;
        <a
          className="ecosystem-artist"
          href="https://app.eddaswap.com/nft-detail?id=63"
          target="_blank"
          rel="noopener noreferrer"
        >
          Marnik
        </a>
        ,&nbsp;
        <a
          className="ecosystem-artist"
          href="https://app.eddaswap.com/nft-detail?id=71"
          target="_blank"
          rel="noopener noreferrer"
        >
          Yana Khvan
        </a>
        ,&nbsp;
        <a
          className="ecosystem-artist"
          href="https://app.eddaswap.com/nft-detail?id=78"
          target="_blank"
          rel="noopener noreferrer"
        >
          BatMax
        </a>
        ,&nbsp;
        <a
          className="ecosystem-artist"
          href="https://app.eddaswap.com/nft-detail?id=67"
          target="_blank"
          rel="noopener noreferrer"
        >
          Space Yacht Labs
        </a>
        ,&nbsp;
        <a
          className="ecosystem-artist"
          href="https://app.eddaswap.com/nft-detail?id=74"
          target="_blank"
          rel="noopener noreferrer"
        >
          D3sert Punk
        </a>
        ,&nbsp;
        <a
          className="ecosystem-artist"
          href="https://app.eddaswap.com/nft-detail?id=30"
          target="_blank"
          rel="noopener noreferrer"
        >
          LayerInsane
        </a>
        ,&nbsp;
        <a
          className="ecosystem-artist"
          href="https://app.eddaswap.com/nft-detail?id=78"
          target="_blank"
          rel="noopener noreferrer"
        >
          Rafi Amar
        </a>
        &nbsp;
        <a
          className="ecosystem-artist"
          href="https://app.eddaswap.com/nft-detail?id=42"
          target="_blank"
          rel="noopener noreferrer"
        >
          Stefan Große Halbuer
        </a>
        ,&nbsp; amongst others. Our NFT platform facilitates the representation
        of unique, real world assets through tokenization on several blockchains
        such as Etheruem, Polygon and Binance Smart Chain. EDDA token holders
        are staking their EDDA or EDDA (UNI-V2) LP tokens in order to earn
        Samurai points. These Samurai points are used to redeem EDDASwap’s
        exclusive NFTs which are being sold on NFT marketplaces such as OpenSea.
        {"   "}
        <span onClick={onToggle} className="ecosystem-more">
          Less
        </span>
      </p>
    ),
    buttonLabel: "EDDASwap NFT",
    link: "https://app.eddaswap.com/nfts",
  },
  {
    id: 3,
    image: "/ecosystem/staking.svg",
    title: "STAKING PLATFORM",
    shortDescription: (
      <p className="ecosystem-description">
        The Staking Platform generates a passive yield for EDDA Token Holders.
        Users are staking EDDA and EDDA (UNI-V2) LP tokens in order to earn more
        EDDA as rewards. 10% of the total EDDA supply has been allocated towards
        staking rewards which are being uniformly distributed over a period of 9
        months. Stakers will continue to earn rewards even after this time
        period as a part of the trading fee generated for the EDDASwap DEX is
        used to buy EDDA from the open market and distributed as staking
        rewards. The current staking APYs can be viewed{" "}
        <a
          className="ecosystem-artist"
          href="https://app.eddaswap.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          here
        </a>
      </p>
    ),
    buttonLabel: "STAKE EDDA",
    link: "https://app.eddaswap.com/staking",
  },
  {
    id: 4,
    image: "/ecosystem/launchpad.svg",
    title: "TURNKEY NFT SERVICES",
    shortDescription: (
      <p className="ecosystem-description">
        EDDASwap offers turnkey NFT services by providing end-to-end execution
        for any NFT venture. This includes conceptualising and creating the
        NFTs, minting them on any leading blockchain, and marketing and
        facilitating their sales to users. Our clients include global brands,
        celebrities such as movie stars and actors, and athletes including
        footballers and NBA players.
      </p>
    ),
    buttonLabel: null,
    link: "",
  },
  {
    id: 5,
    image: "/ecosystem/eddaverse.svg",
    title: "EDDAVerse",
    shortDescription: (
      <p className="ecosystem-description">
        EDDAVerse is the ultimate version of the metaverse, bringing never
        before seen AR and VR technology, combined with state-of-the-art NFTs,
        to blur the line between the physical and virtual worlds. EDDASwap’s
        established pedigree in 360° VR NFTs and digital art has been dialed up
        to the next level, to deliver a mind-blowing and futuristic metaverse
        experience. EDDASwap is also the metaverse execution partner for some of
        the world’s largest celebrities and brands, including movie stars,
        actors, and athletes such as footballers, NBA players, cricketers, and
        UFC fighters. Powered by EDDASwap, fans around the world will be able to
        experience and interact with their idols in the metaverse like never
        before.
      </p>
    ),
    buttonLabel: null,
    link: "",
  },
  {
    id: 6,
    image: "/ecosystem/physical.svg",
    title: "Physical Collectibles",
    shortDescription: (
      <p className="ecosystem-description">
        EDDASwap’s trailblazing NFTs have established themselves as the most
        sought-after digital works of art in the industry, and now EDDASwap has
        expanded its artistic vision to the world of physical collectibles. The
        first EDDASwap branded physical collection is an exquisite,
        limited-edition collection of 999 Gandhi themed silver coins that are
        also functional ETH wallets.
      </p>
    ),
    buttonLabel: null,
    link: "",
  },
];
