import React, { useState } from "react";
import Fade from "react-reveal/Fade";

import "./index.css";

import Lottie from "lottie-react";
import animationData from "./line.json";

const Ecosystem = () => {
  const [expand, setExpand] = useState(false);
  const onToggleExpand = () => setExpand(!expand);
  return (
    <div className="eco-container" id="ecosystem">
      <div className="ecosystem-title">EDDASwap Ecosystem</div>
      <div className="ecosystem-wrapper">
        <div className="ecosystem-item eco-decentralized">
          <Fade bottom>
            <div className="ecosystem-item-title">
              01. DECENTRALIZED EXCHANGE
            </div>
          </Fade>
          <Fade bottom delay="500">
            <div
              className="ecosystem-description"
              style={{ marginBottom: "64px" }}
            >
              <p className="">
                The EDDASwap DEX facilitates permission-less listing and trading
                of crypto assets across blockchains such as Polygon (MATIC) and
                Binance Smart Chain. EDDASwap has added security features such
                as "Liquidity Lock", whereby users that list their token onto
                EDDASwap will have the ability to lock in the liquidity to gain
                trust and credibility. A part of the trading fees generated on
                the DEX will be used to buy EDDA tokens from the open market and
                the same will be distributed to those staking EDDA. The LP
                tokens generated by providing liquidity to the EDDASwap DEX can
                be staked to earn a range of benefits such as EDDASwap's
                exclusive NFTs.
              </p>
            </div>
            <Fade bottom delay="1000">
              <a
                className="ecosystem-btn edda-button edda-dex-button"
                target="_blank"
                rel="noopener noreferrer"
                href="https://dex.eddaswap.com/exchange"
              >
                EDDASwap DEX
              </a>
            </Fade>
            {/* <img src="/ecosystem/exchange.svg" className="exchange-img" /> */}
          </Fade>
        </div>
        <div className="ecosystem-item eco-nft">
          <Fade bottom>
            <div className="ecosystem-item-title">
              02. NON-FUNGIBLE TOKENS (NFT)
            </div>
          </Fade>
          <Fade bottom delay="500">
            <div className="ecosystem-description">
              {!expand && (
                <>
                  <p className="">
                    Our <span>NFT platform</span> is live since March 2021.
                    EDDASwap has partnered with leading global artists, 3D
                    motion graphic designers and producers to create a specially
                    curated NFT collection which has been in production since Q2
                    2020. Our Ultra Rare NFTs have gone viral globally and have
                    been shared, retweeted and posted by Cameron Winklevoss,
                    Tyler Winklevoss, Jason A Williams and many global
                    influencers. EDDA token holders and stakers have exclusive
                    access to EDDASwap’s NFT collection created by well-known
                    artists including&nbsp;
                    <a
                      className="ecosystem-artist"
                      href="https://app.eddaswap.com/nft-detail?id=52"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      OZ
                    </a>
                    ,&nbsp;
                    <a
                      className="ecosystem-artist"
                      href="https://app.eddaswap.com/nft-detail?id=81"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      Cyrus James Khan
                    </a>
                    ,&nbsp;
                    <a
                      className="ecosystem-artist"
                      href="https://app.eddaswap.com/nft-detail?id=13"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      Primal Cypher
                    </a>
                    ,&nbsp;
                    <a
                      className="ecosystem-artist"
                      href="https://app.eddaswap.com/nft-detail?id=63"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      Marnik
                    </a>
                    ,&nbsp;
                    <a
                      className="ecosystem-artist"
                      href="https://app.eddaswap.com/nft-detail?id=71"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      Yana Khvan
                    </a>
                    ,&nbsp;
                    <a
                      className="ecosystem-artist"
                      href="https://app.eddaswap.com/nft-detail?id=78"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      BatMax
                    </a>
                    ,&nbsp; ...
                  </p>
                  <p
                    onClick={onToggleExpand}
                    style={{ fontWeight: "700", marginTop: "32px" }}
                  >
                    Expand <img src="/ecosystem/expand.svg" />
                  </p>
                </>
              )}
              {expand && (
                <>
                  <p className="ecosystem-description">
                    Our NFT platform is live since March 2021. EDDASwap has
                    partnered with leading global artists, 3D motion graphic
                    designers and producers to create a specially curated NFT
                    collection which has been in production since Q2 2020. Our
                    Ultra Rare NFTs have gone viral globally and have been
                    shared, retweeted and posted by Cameron Winklevoss, Tyler
                    Winklevoss, Jason A Williams and many global influencers.
                    EDDA token holders and stakers have exclusive access to
                    EDDASwap’s NFT collection created by well-known artists
                    including&nbsp;
                    <a
                      className="ecosystem-artist"
                      href="https://app.eddaswap.com/nft-detail?id=52"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      OZ
                    </a>
                    ,&nbsp;
                    <a
                      className="ecosystem-artist"
                      href="https://app.eddaswap.com/nft-detail?id=81"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      Cyrus James Khan
                    </a>
                    ,&nbsp;
                    <a
                      className="ecosystem-artist"
                      href="https://app.eddaswap.com/nft-detail?id=13"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      Primal Cypher
                    </a>
                    ,&nbsp;
                    <a
                      className="ecosystem-artist"
                      href="https://app.eddaswap.com/nft-detail?id=63"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      Marnik
                    </a>
                    ,&nbsp;
                    <a
                      className="ecosystem-artist"
                      href="https://app.eddaswap.com/nft-detail?id=71"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      Yana Khvan
                    </a>
                    ,&nbsp;
                    <a
                      className="ecosystem-artist"
                      href="https://app.eddaswap.com/nft-detail?id=78"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      BatMax
                    </a>
                    ,&nbsp;
                    <a
                      className="ecosystem-artist"
                      href="https://app.eddaswap.com/nft-detail?id=67"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      Space Yacht Labs
                    </a>
                    ,&nbsp;
                    <a
                      className="ecosystem-artist"
                      href="https://app.eddaswap.com/nft-detail?id=74"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      D3sert Punk
                    </a>
                    ,&nbsp;
                    <a
                      className="ecosystem-artist"
                      href="https://app.eddaswap.com/nft-detail?id=30"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      LayerInsane
                    </a>
                    ,&nbsp;
                    <a
                      className="ecosystem-artist"
                      href="https://app.eddaswap.com/nft-detail?id=78"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      Rafi Amar
                    </a>
                    &nbsp;
                    <a
                      className="ecosystem-artist"
                      href="https://app.eddaswap.com/nft-detail?id=42"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      Stefan Große Halbuer
                    </a>
                    ,&nbsp; amongst others. Our NFT platform facilitates the
                    representation of unique, real world assets through
                    tokenization on several blockchains such as Etheruem,
                    Polygon and Binance Smart Chain. EDDA token holders are
                    staking their EDDA or EDDA (UNI-V2) LP tokens in order to
                    earn Samurai points. These Samurai points are used to redeem
                    EDDASwap’s exclusive NFTs which are being sold on NFT
                    marketplaces such as OpenSea.
                  </p>
                  <p onClick={onToggleExpand}>
                    Show Less <img src="/ecosystem/expand.svg" />
                  </p>
                </>
              )}
            </div>
            <Fade bottom delay="1000">
              <a
                className="ecosystem-btn edda-button"
                target="_blank"
                rel="noopener noreferrer"
                href="https://app.eddaswap.com/nfts"
              >
                EDDASwap NFT
              </a>
            </Fade>
            <div className="ecosystem-lottie">
              <Lottie animationData={animationData} />
            </div>
          </Fade>
          {/* <img src="/ecosystem/nft.svg" className="nft-img" /> */}
        </div>
        {/* <div className="ecosystem-item">
          <div className="ecosystem-item-title">03. STAKING PLATFORM</div>
          <div className="ecosystem-description">
            <p className="">
              The Staking Platform generates a passive yield for EDDA Token
              Holders. Users are staking EDDA and EDDA (UNI-V2) LP tokens in
              order to earn more EDDA as rewards. 10% of the total EDDA supply
              has been allocated towards staking rewards which are being
              uniformly distributed over a period of 9 months. Stakers will
              continue to earn rewards even after this time period as a part of
              the trading fee generated for the EDDASwap DEX is used to buy EDDA
              from the open market and distributed as staking rewards. The
              current staking APYs can be viewed{" "}
              <a
                className="ecosystem-artist"
                href="https://app.eddaswap.com/"
                target="_blank"
                rel="noopener noreferrer"
              >
                here
              </a>
            </p>
          </div>
          <a
            className="ecosystem-btn edda-button"
            target="_blank"
            rel="noopener noreferrer"
            href="https://app.eddaswap.com/staking"
          >
            Stake EDDA
          </a>
        </div> */}
        <div className="ecosystem-item eco-turnkey">
          <Fade bottom>
            <div className="ecosystem-item-title">03. TURNKEY NFT SERVICES</div>
          </Fade>
          <Fade bottom delay="500">
            <div className="ecosystem-description">
              <p className="">
                EDDASwap offers turnkey NFT services by providing end-to-end
                execution for any NFT venture. This includes conceptualising and
                creating the NFTs, minting them on any leading blockchain, and
                marketing and facilitating their sales to users. Our clients
                include global brands, celebrities such as movie stars and
                actors, and athletes including footballers and NBA players.
              </p>
            </div>
          </Fade>
          {/* <img src="/ecosystem/turnkey.svg" className="turnkey-img" /> */}
        </div>
        <div className="ecosystem-item eco-eddaverse">
          <Fade bottom>
            <div className="ecosystem-item-title">04. EDDAVerse</div>
          </Fade>
          <Fade bottom delay="500">
            <div className="ecosystem-description">
              <p className="" style={{ marginBottom: "20px" }}>
                EDDAVerse is the ultimate metaverse, combining state-of-the-art
                VR technology with signature EDDAVerse NFTs, to blur the line
                between the physical and virtual worlds. EDDASwap’s established
                pedigree in 360° VR NFTs and digital art has been dialed up to
                the next level, to deliver a mind-blowing and futuristic
                metaverse experience.
              </p>
              <p className="">
                EDDAVerse is also the metaverse execution partner for some of
                the world’s largest celebrities and brands, including movie
                stars, actors, and athletes such as footballers, NBA players,
                cricketers, and UFC fighters. Powered by EDDAVerse, fans around
                the world will be able to experience and interact with their
                idols in the metaverse like never before.
              </p>

              <div className="ecosystem-lottie">
                <Lottie animationData={animationData} />
              </div>
            </div>
          </Fade>
          {/* <img src="/ecosystem/eddaverse.svg" className="eddaverse-img" /> */}
        </div>
        <div
          className="ecosystem-item eco-physical"
          style={{ paddingBottom: "400px" }}
        >
          <Fade bottom>
            <div className="ecosystem-item-title">
              05. PHYSICAL COLLECTIBLES
            </div>
          </Fade>
          <Fade bottom delay="500">
            <div className="ecosystem-description">
              <p className="" style={{ marginBottom: "20px " }}>
                EDDASwap’s Staking Platform 2.0 has been revamped with a never
                before seen twist: staking for physical collectibles! EDDASwap’s
                trailblazing NFTs have established themselves as the most
                sought-after digital works of art in the industry, and now
                EDDASwap has expanded its artistic vision to the world of
                physical collectibles.{" "}
              </p>
              <p style={{ marginBottom: "20px " }}>
                The first EDDASwap branded physical collection is an exquisite,
                limited-edition collection of 80 EDDASwap and Gandhi themed pure
                silver coins that are also functional ETH wallets! Etched on
                each coin will be a hologram with a private key to access the
                corresponding ETH wallet. Each wallet will be pre-loaded with
                0.02 ETH as a bonus. Like any other wallet, you will be able to
                send and receive ERC-20 tokens, NFTs, and everything else.
              </p>
              <p style={{ marginBottom: "32px " }}>
                {" "}
                These silver coins are just the first of many ultra high-end,
                luxury collectibles that will be made available to stakers
                through the new platform, with several additions coming soon,
                including luxury custom-made Swiss watches!
              </p>
              <Fade bottom delay="1000">
                <a
                  className="ecosystem-btn edda-button"
                  target="_blank"
                  rel="noopener noreferrer"
                  href="https://app.eddaswap.com/ag"
                  style={{ marginBottom: "0px" }}
                >
                  Stake EDDA
                </a>
              </Fade>
            </div>
          </Fade>
          {/* <img src="/ecosystem/physical.svg" className="physical-img" /> */}
        </div>
      </div>
    </div>
  );
};

export default Ecosystem;
